source:
  branch: main
  path: ./index.md

theme: minima

plugins:
  - jekyll-feed
  - jekyll-sitemap

url: https://alavuvi.github.io/

title: My GitHub Pages Site
description: This is my awesome GitHub Pages site.
author: Your Name